format = """$fill
$character"""
right_format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$battery\
$time\
$status\
"""

[fill]
symbol = "â”"

[character]
success_symbol = "[â¯](bold #5a28ff)[â¯](bold cyan)[â¯](bold green)"
error_symbol = "[â¯â¯â¯](bold red)"
vimcmd_symbol = "[â®â®â®](bold cyan)"
vimcmd_visual_symbol = "[â®â®â®](bold yellow)"

[git_branch]
symbol = "ğŸŒ± "
style = "green"

[golang]
symbol = "Go "

[java]
symbol = "Java "
style = "blue"

[ruby]
disabled = true

[swift]
disabled = true

[perl]
disabled = true
