format = """$fill
$hostname$character"""
right_format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$battery\
$time\
$status\
"""

[fill]
symbol = "â”"

[character]
success_symbol = "[|>](bold #5a28ff)[|>](bold cyan)[|>](bold green)"
error_symbol = "[|>|>|>](bold red)"
vimcmd_symbol = "[<|<|<|](bold cyan)"
vimcmd_visual_symbol = "[<|<|<|](bold yellow)"

[git_branch]
style = "green"

[hostname]
style = "cyan"
